-- Email Verification Tokens Table
create table if not exists email_verifications (
  id bigint generated by default as identity primary key,
  email text not null,
  token text not null unique,
  expires_at timestamp with time zone not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  verified_at timestamp with time zone,
  used_at timestamp with time zone
);

-- Index for faster lookups
create index if not exists idx_email_verifications_email_token on email_verifications(email, token);
create index if not exists idx_email_verifications_token on email_verifications(token);
create index if not exists idx_email_verifications_expires_at on email_verifications(expires_at);

-- RLS Policy
alter table email_verifications enable row level security;

create policy "Users can verify their own email" on email_verifications
  for all using (true); -- Public access since we're using token-based verification