'use client';

import { useState, useEffect } from 'react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Download, FileText, Printer } from 'lucide-react';
import { db, ZReport as ZReportData } from '@/lib/db/database';
import { useAuth } from '@/lib/auth';
import { useCurrentTenant } from '@/lib/tenant-context';
import { format } from 'date-fns';
import { generateAndStoreZReport } from '@/lib/reports';
import { ReportGenerator, reportUtils } from '@/lib/report-generator';

export default function ZReport() {
  const { user } = useAuth();
  const { tenantId } = useCurrentTenant();
  const [reports, setReports] = useState<ZReportData[]>([]);
  const [selectedReport, setSelectedReport] = useState<ZReportData | null>(null);
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    loadReports();
  }, []);

  const loadReports = async () => {
    setLoading(true);
    try {
      const allReports = await db.zReports.orderBy('generatedAt').reverse().toArray();
      
      // Filter by tenant if tenantId is available
      const filteredReports = tenantId ? 
        allReports.filter(report => report.staffId === user?.id) : 
        allReports;
        
      setReports(filteredReports);
    } catch (error) {
      console.error("Error loading Z-Reports:", error);
    } finally {
      setLoading(false);
    }
  };

  const handleGenerateReport = async () => {
    if (!user) return;
    setLoading(true);
    try {
      const reportGenerated = await generateAndStoreZReport(user.id!, user.name);
      if (reportGenerated) {
        alert("Z-Report generated successfully.");
        await loadReports(); // Refresh the list
      } else {
        alert("No sales recorded for today. Z-Report not generated.");
      }
    } catch (error) {
      console.error("Error generating Z-Report:", error);
      alert("Failed to generate Z-Report. Please check the console for details.");
    } finally {
      setLoading(false);
    }
  };

  const formatCurrency = (amount: number) => {
    return reportUtils.formatCurrency(amount);
  };

  const handleExportPDF = () => {
    if (!selectedReport) return;
    
    const reportData = {
      reportDate: selectedReport.reportDate,
      totalSales: selectedReport.totalSales,
      totalTransactions: selectedReport.totalTransactions,
      salesByPaymentMethod: selectedReport.salesByPaymentMethod,
      totalTax: selectedReport.totalTax,
      totalDiscount: selectedReport.totalDiscount,
      staffName: selectedReport.staffName,
      generatedAt: selectedReport.generatedAt
    };
    
    const filename = reportUtils.getFileName(`Z_Report_${format(selectedReport.reportDate, 'yyyy-MM-dd')}`, 'pdf');
    ReportGenerator.exportToPDF(reportData, `Z-Report - ${format(selectedReport.reportDate, 'PPP')}`, filename);
  };

  const handleExportCSV = () => {
    if (!selectedReport) return;
    
    const csvData = [{
      'Report Date': format(selectedReport.reportDate, 'PPP'),
      'Generated At': format(selectedReport.generatedAt, 'PPP p'),
      'Staff Name': selectedReport.staffName,
      'Total Sales': selectedReport.totalSales,
      'Total Transactions': selectedReport.totalTransactions,
      'Total Tax': selectedReport.totalTax,
      'Total Discount': selectedReport.totalDiscount,
      'Cash Sales': selectedReport.salesByPaymentMethod.cash,
      'Mobile Money Sales': selectedReport.salesByPaymentMethod.mobile_money,
      'Bank Card Sales': selectedReport.salesByPaymentMethod.bank_card,
      'Credit Sales': selectedReport.salesByPaymentMethod.credit
    }];
    
    const headers = ['Report Date', 'Generated At', 'Staff Name', 'Total Sales', 'Total Transactions', 'Total Tax', 'Total Discount', 'Cash Sales', 'Mobile Money Sales', 'Bank Card Sales', 'Credit Sales'];
    const filename = reportUtils.getFileName(`Z_Report_${format(selectedReport.reportDate, 'yyyy-MM-dd')}`, 'csv');
    ReportGenerator.exportToCSV(csvData, headers, filename);
  };

  const handlePrint = () => {
    if (!selectedReport) return;
    
    const content = `
      <div class="summary">
        <div class="summary-item"><strong>Report Date:</strong> ${format(selectedReport.reportDate, 'PPP')}</div>
        <div class="summary-item"><strong>Generated By:</strong> ${selectedReport.staffName}</div>
        <div class="summary-item"><strong>Generated At:</strong> ${format(selectedReport.generatedAt, 'PPP p')}</div>
        <div class="summary-item"><strong>Total Sales:</strong> ${formatCurrency(selectedReport.totalSales)}</div>
        <div class="summary-item"><strong>Total Transactions:</strong> ${selectedReport.totalTransactions}</div>
        <div class="summary-item"><strong>Total Tax:</strong> ${formatCurrency(selectedReport.totalTax)}</div>
        <div class="summary-item"><strong>Total Discount:</strong> ${formatCurrency(selectedReport.totalDiscount)}</div>
      </div>
      
      <h3>Sales by Payment Method</h3>
      <table>
        <tr><th>Payment Method</th><th>Amount</th></tr>
        <tr><td>Cash</td><td>${formatCurrency(selectedReport.salesByPaymentMethod.cash)}</td></tr>
        <tr><td>Mobile Money</td><td>${formatCurrency(selectedReport.salesByPaymentMethod.mobile_money)}</td></tr>
        <tr><td>Bank Card</td><td>${formatCurrency(selectedReport.salesByPaymentMethod.bank_card)}</td></tr>
        <tr><td>Credit</td><td>${formatCurrency(selectedReport.salesByPaymentMethod.credit)}</td></tr>
      </table>
    `;
    
    ReportGenerator.printReport(`Z-Report - ${format(selectedReport.reportDate, 'PPP')}`, content);
  };

  return (
    <div>
      <div className="flex items-center justify-between mb-6">
        <h2 className="text-2xl font-bold text-gray-900">Z-Report (End of Day)</h2>
        {user?.role !== 'cashier' && (
          <Button onClick={handleGenerateReport} disabled={loading}>
            {loading ? 'Generating...' : 'Generate for Today'}
          </Button>
        )}
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <div className="md:col-span-1">
          <Card>
            <CardHeader>
              <CardTitle>Historical Reports</CardTitle>
            </CardHeader>
            <CardContent>
              {loading && <p>Loading reports...</p>}
              {!loading && reports.length === 0 && <p>No reports found.</p>}
              <div className="space-y-2">
                {reports.map(report => (
                  <button
                    key={report.id}
                    onClick={() => setSelectedReport(report)}
                    className={`w-full text-left p-2 rounded-lg text-sm transition-colors ${
                      selectedReport?.id === report.id
                        ? 'bg-blue-100 text-blue-800 font-semibold'
                        : 'hover:bg-gray-100'
                    }`}
                  >
                    <p className="font-medium">{format(report.reportDate, 'PPP')}</p>
                    <p className="text-xs text-gray-500">by {report.staffName}</p>
                  </button>
                ))}
              </div>
            </CardContent>
          </Card>
        </div>

        <div className="md:col-span-2">
          {selectedReport ? (
            <Card>
              <CardHeader>
                <div className="flex items-center justify-between">
                  <CardTitle>Z-Report for {format(selectedReport.reportDate, 'PPP')}</CardTitle>
                  <div className="flex gap-2">
                    <Button variant="outline" size="sm" onClick={handleExportPDF}>
                      <Download className="h-4 w-4 mr-2" />
                      PDF
                    </Button>
                    <Button variant="outline" size="sm" onClick={handleExportCSV}>
                      <FileText className="h-4 w-4 mr-2" />
                      CSV
                    </Button>
                    <Button variant="outline" size="sm" onClick={handlePrint}>
                      <Printer className="h-4 w-4 mr-2" />
                      Print
                    </Button>
                  </div>
                </div>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div className="p-4 border rounded-lg">
                    <h3 className="font-semibold text-lg mb-2">Summary</h3>
                    <div className="space-y-1">
                      <div className="flex justify-between"><span>Total Sales:</span> <span className="font-mono">{formatCurrency(selectedReport.totalSales)}</span></div>
                      <div className="flex justify-between"><span>Total Transactions:</span> <span className="font-mono">{selectedReport.totalTransactions}</span></div>
                      <div className="flex justify-between"><span>Total Tax:</span> <span className="font-mono">{formatCurrency(selectedReport.totalTax)}</span></div>
                      <div className="flex justify-between"><span>Total Discount:</span> <span className="font-mono">{formatCurrency(selectedReport.totalDiscount)}</span></div>
                    </div>
                  </div>
                  <div className="p-4 border rounded-lg">
                    <h3 className="font-semibold text-lg mb-2">Sales by Payment Method</h3>
                    <div className="space-y-1">
                      <div className="flex justify-between"><span>Cash:</span> <span className="font-mono">{formatCurrency(selectedReport.salesByPaymentMethod.cash)}</span></div>
                      <div className="flex justify-between"><span>Mobile Money:</span> <span className="font-mono">{formatCurrency(selectedReport.salesByPaymentMethod.mobile_money)}</span></div>
                      <div className="flex justify-between"><span>Bank Card:</span> <span className="font-mono">{formatCurrency(selectedReport.salesByPaymentMethod.bank_card)}</span></div>
                      <div className="flex justify-between"><span>Credit:</span> <span className="font-mono">{formatCurrency(selectedReport.salesByPaymentMethod.credit)}</span></div>
                    </div>
                  </div>
                </div>
                <div className="text-xs text-gray-500 pt-4 border-t">
                  <p>Generated by: {selectedReport.staffName}</p>
                  <p>Generated at: {format(selectedReport.generatedAt, 'PPP p')}</p>
                </div>
              </CardContent>
            </Card>
          ) : (
            <div className="text-center py-12 text-gray-500">
              <p>Select a report from the list to view its details.</p>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
