# Generated by Django 4.2.27 on 2026-01-14 01:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('subdomain', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('industry', models.CharField(choices=[('retail', 'Retail'), ('pharmacy', 'Pharmacy'), ('service', 'Service System'), ('restaurant', 'Restaurant/Hospitality'), ('manufacturing', 'Manufacturing')], default='retail', max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='tenants/logos/')),
                ('primary_color', models.CharField(default='#3B82F6', max_length=7)),
                ('subscription_tier', models.CharField(choices=[('free', 'Free'), ('starter', 'Starter'), ('professional', 'Professional'), ('enterprise', 'Enterprise')], default='free', max_length=20)),
                ('subscription_expires', models.DateField(blank=True, null=True)),
                ('active_modules', models.JSONField(blank=True, default=dict)),
                ('enable_multi_site', models.BooleanField(default=True)),
                ('max_branches', models.IntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50)),
                ('is_hq', models.BooleanField(default=False)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('parent_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_branches', to='tenants.branch')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='tenants.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'code')},
            },
        ),
    ]
