-- Tenants Table (For Multi-tenancy)
create table if not exists tenants (
  id bigint generated by default as identity primary key,
  uuid uuid default gen_random_uuid() not null unique,
  name text not null,
  slug text unique, -- For custom domains/links
  plan text default 'free',
  owner_id uuid, -- Supabase Auth user ID of owner
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Staff Table (Users)
create table if not exists staff (
  id bigint generated by default as identity primary key,
  uuid uuid not null unique, -- Supabase Auth user ID
  tenant_id bigint references tenants(id), -- Link to tenant
  username text,
  password text, -- Hashed
  pin text,
  name text not null,
  email text,
  phone text,
  role text default 'cashier',
  permissions jsonb default '{}'::jsonb, -- Store permissions object
  is_active boolean default true,
  last_login timestamp with time zone,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Products Table
create table if not exists products (
  id bigint generated by default as identity primary key,
  uuid uuid default gen_random_uuid() not null unique,
  tenant_id bigint references tenants(id), -- Link to tenant
  sku text,
  name text not null,
  description text,
  cost_price numeric default 0,
  selling_price numeric default 0,
  category text,
  stock_quantity integer default 0,
  reorder_level integer default 5,
  barcodes text[],
  image_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Sales Table
create table if not exists sales (
  id bigint generated by default as identity primary key,
  uuid uuid default gen_random_uuid() not null unique,
  tenant_id bigint references tenants(id), -- Link to tenant
  receipt_number text not null,
  subtotal numeric default 0,
  discount_amount numeric default 0,
  tax_amount numeric default 0,
  total_amount numeric default 0,
  paid_amount numeric default 0,
  change_amount numeric default 0,
  payment_method text,
  staff_id bigint, -- Link to staff ID
  staff_name text,
  items jsonb,
  status text default 'completed',
  sync_status text default 'synced',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS Policies
alter table tenants enable row level security;
alter table staff enable row level security;
alter table products enable row level security;
alter table sales enable row level security;

-- Simplified Policies (Update these for production!)
create policy "Public Access" on tenants for all using (true);
create policy "Public Access" on staff for all using (true);
create policy "Public Access" on products for all using (true);
create policy "Public Access" on sales for all using (true);
