// Employees Data
export const employeesData = [
    {
        id: 'emp-0001',
        firstName: 'Sarah',
        lastName: 'Johnson',
        email: 'sarah.johnson@company.com',
        phone: '+1 (555) 123-4567',
        department: 'Engineering',
        position: 'Senior Software Engineer',
        salary: 95000,
        startDate: '2022-03-15',
        employmentType: 'full-time',
        status: 'active',
        manager: 'emp-0002',
        location: 'New York',
        skills: ['React', 'Node.js', 'Python'],
    },
    {
        id: 'emp-0002',
        firstName: 'Michael',
        lastName: 'Chen',
        email: 'michael.chen@company.com',
        phone: '+1 (555) 234-5678',
        department: 'Engineering',
        position: 'Engineering Manager',
        salary: 125000,
        startDate: '2021-01-10',
        employmentType: 'full-time',
        status: 'active',
        manager: null,
        location: 'New York',
        skills: ['Leadership', 'System Architecture', 'Agile'],
    },
    {
        id: 'emp-0003',
        firstName: 'Emily',
        lastName: 'Davis',
        email: 'emily.davis@company.com',
        phone: '+1 (555) 345-6789',
        department: 'Marketing',
        position: 'Marketing Manager',
        salary: 85000,
        startDate: '2021-06-01',
        employmentType: 'full-time',
        status: 'active',
        manager: null,
        location: 'San Francisco',
        skills: ['Digital Marketing', 'SEO', 'Content Strategy'],
    },
    {
        id: 'emp-0004',
        firstName: 'James',
        lastName: 'Wilson',
        email: 'james.wilson@company.com',
        phone: '+1 (555) 456-7890',
        department: 'Sales',
        position: 'Sales Representative',
        salary: 65000,
        startDate: '2023-01-15',
        employmentType: 'full-time',
        status: 'active',
        manager: 'emp-0005',
        location: 'Chicago',
        skills: ['CRM', 'Negotiation', 'Client Relations'],
    },
    {
        id: 'emp-0005',
        firstName: 'Lisa',
        lastName: 'Anderson',
        email: 'lisa.anderson@company.com',
        phone: '+1 (555) 567-8901',
        department: 'Sales',
        position: 'Sales Director',
        salary: 110000,
        startDate: '2020-09-01',
        employmentType: 'full-time',
        status: 'active',
        manager: null,
        location: 'Chicago',
        skills: ['Sales Strategy', 'Team Leadership', 'Account Management'],
    },
    {
        id: 'emp-0006',
        firstName: 'David',
        lastName: 'Martinez',
        email: 'david.martinez@company.com',
        phone: '+1 (555) 678-9012',
        department: 'HR',
        position: 'HR Specialist',
        salary: 70000,
        startDate: '2022-08-01',
        employmentType: 'full-time',
        status: 'active',
        manager: 'emp-0007',
        location: 'New York',
        skills: ['Recruitment', 'Employee Relations', 'HRIS'],
    },
    {
        id: 'emp-0007',
        firstName: 'Jennifer',
        lastName: 'Taylor',
        email: 'jennifer.taylor@company.com',
        phone: '+1 (555) 789-0123',
        department: 'HR',
        position: 'HR Director',
        salary: 105000,
        startDate: '2019-04-15',
        employmentType: 'full-time',
        status: 'active',
        manager: null,
        location: 'New York',
        skills: ['HR Strategy', 'Talent Management', 'Compliance'],
    },
    {
        id: 'emp-0008',
        firstName: 'Robert',
        lastName: 'Brown',
        email: 'robert.brown@company.com',
        phone: '+1 (555) 890-1234',
        department: 'Finance',
        position: 'Financial Analyst',
        salary: 75000,
        startDate: '2022-11-01',
        employmentType: 'full-time',
        status: 'active',
        manager: 'emp-0009',
        location: 'New York',
        skills: ['Financial Analysis', 'Excel', 'Forecasting'],
    },
    {
        id: 'emp-0009',
        firstName: 'Maria',
        lastName: 'Garcia',
        email: 'maria.garcia@company.com',
        phone: '+1 (555) 901-2345',
        department: 'Finance',
        position: 'CFO',
        salary: 180000,
        startDate: '2018-07-01',
        employmentType: 'full-time',
        status: 'active',
        manager: null,
        location: 'New York',
        skills: ['Financial Strategy', 'Risk Management', 'Leadership'],
    },
];

// Departments Data
export const departmentsData = [
    { id: 'dept-001', name: 'Engineering', head: 'Michael Chen', employeeCount: 45, budget: 4500000 },
    { id: 'dept-002', name: 'Marketing', head: 'Emily Davis', employeeCount: 12, budget: 1200000 },
    { id: 'dept-003', name: 'Sales', head: 'Lisa Anderson', employeeCount: 28, budget: 2800000 },
    { id: 'dept-004', name: 'HR', head: 'Jennifer Taylor', employeeCount: 8, budget: 800000 },
    { id: 'dept-005', name: 'Finance', head: 'Maria Garcia', employeeCount: 15, budget: 1500000 },
    { id: 'dept-006', name: 'Operations', head: 'James Wilson', employeeCount: 20, budget: 2000000 },
    { id: 'dept-007', name: 'Customer Support', head: 'Sarah Johnson', employeeCount: 18, budget: 1800000 },
    { id: 'dept-008', name: 'Product', head: 'David Martinez', employeeCount: 10, budget: 1000000 },
];

// Attendance Data
export const attendanceData = [
    {
        id: 'att-0001',
        employeeId: 'emp-0001',
        date: '2026-02-09',
        clockIn: '2026-02-09T09:00:00',
        clockOut: '2026-02-09T17:30:00',
        breakTime: 60,
        hoursWorked: 7.5,
        status: 'present',
        overtime: 0,
    },
    {
        id: 'att-0002',
        employeeId: 'emp-0002',
        date: '2026-02-09',
        clockIn: '2026-02-09T08:45:00',
        clockOut: '2026-02-09T18:15:00',
        breakTime: 60,
        hoursWorked: 8.5,
        status: 'present',
        overtime: 0.5,
    },
    {
        id: 'att-0003',
        employeeId: 'emp-0003',
        date: '2026-02-09',
        clockIn: '2026-02-09T09:15:00',
        clockOut: '2026-02-09T17:45:00',
        breakTime: 60,
        hoursWorked: 7.5,
        status: 'present',
        overtime: 0,
    },
    {
        id: 'att-0004',
        employeeId: 'emp-0004',
        date: '2026-02-09',
        clockIn: null,
        clockOut: null,
        breakTime: 0,
        hoursWorked: 0,
        status: 'absent',
        overtime: 0,
        reason: 'Sick leave',
    },
    {
        id: 'att-0005',
        employeeId: 'emp-0005',
        date: '2026-02-09',
        clockIn: '2026-02-09T08:30:00',
        clockOut: '2026-02-09T17:00:00',
        breakTime: 60,
        hoursWorked: 7.5,
        status: 'present',
        overtime: 0,
    },
];

// Leave Requests Data
export const leaveRequestsData = [
    {
        id: 'leave-0001',
        employeeId: 'emp-0001',
        type: 'annual',
        startDate: '2026-02-15',
        endDate: '2026-02-19',
        daysRequested: 5,
        reason: 'Family vacation',
        status: 'pending',
        requestedDate: '2026-02-01',
        approver: null,
        approvedDate: null,
    },
    {
        id: 'leave-0002',
        employeeId: 'emp-0003',
        type: 'sick',
        startDate: '2026-02-10',
        endDate: '2026-02-11',
        daysRequested: 2,
        reason: 'Medical appointment',
        status: 'approved',
        requestedDate: '2026-02-08',
        approver: 'emp-0007',
        approvedDate: '2026-02-08',
    },
    {
        id: 'leave-0003',
        employeeId: 'emp-0004',
        type: 'personal',
        startDate: '2026-02-20',
        endDate: '2026-02-21',
        daysRequested: 2,
        reason: 'Personal matters',
        status: 'pending',
        requestedDate: '2026-02-05',
        approver: null,
        approvedDate: null,
    },
    {
        id: 'leave-0004',
        employeeId: 'emp-0006',
        type: 'maternity',
        startDate: '2026-03-01',
        endDate: '2026-06-30',
        daysRequested: 90,
        reason: 'Maternity leave',
        status: 'approved',
        requestedDate: '2026-01-15',
        approver: 'emp-0007',
        approvedDate: '2026-01-20',
    },
];

// Payroll Data
export const payrollData = [
    {
        id: 'pay-0001',
        employeeId: 'emp-0001',
        period: '2026-01',
        payDate: '2026-01-31',
        baseSalary: 7916.67,
        overtime: 250.00,
        bonuses: 500.00,
        grossPay: 8666.67,
        federalTax: 1733.33,
        stateTax: 693.33,
        socialSecurity: 537.33,
        medicare: 125.67,
        otherDeductions: 100.00,
        netPay: 5476.67,
        status: 'paid',
        paymentMethod: 'direct_deposit',
    },
    {
        id: 'pay-0002',
        employeeId: 'emp-0002',
        period: '2026-01',
        payDate: '2026-01-31',
        baseSalary: 10416.67,
        overtime: 0,
        bonuses: 1000.00,
        grossPay: 11416.67,
        federalTax: 2283.33,
        stateTax: 913.33,
        socialSecurity: 707.83,
        medicare: 165.50,
        otherDeductions: 150.00,
        netPay: 7196.68,
        status: 'paid',
        paymentMethod: 'direct_deposit',
    },
    {
        id: 'pay-0003',
        employeeId: 'emp-0003',
        period: '2026-01',
        payDate: '2026-01-31',
        baseSalary: 7083.33,
        overtime: 0,
        bonuses: 750.00,
        grossPay: 7833.33,
        federalTax: 1566.67,
        stateTax: 626.67,
        socialSecurity: 485.67,
        medicare: 113.58,
        otherDeductions: 100.00,
        netPay: 4940.74,
        status: 'paid',
        paymentMethod: 'direct_deposit',
    },
];

// Performance Data
export const performanceData = [
    {
        id: 'perf-0001',
        employeeId: 'emp-0001',
        reviewPeriod: '2025-Q4',
        reviewDate: '2026-01-15',
        reviewer: 'emp-0002',
        overallRating: 4.5,
        technicalSkills: 4.8,
        communication: 4.2,
        teamwork: 4.5,
        leadership: 3.8,
        productivity: 4.6,
        goals: [
            { goal: 'Complete React certification', status: 'completed', weight: 0.3 },
            { goal: 'Mentor junior developers', status: 'in_progress', weight: 0.4 },
            { goal: 'Improve code review process', status: 'completed', weight: 0.3 },
        ],
        strengths: ['Strong technical skills', 'Good problem-solving', 'Team player'],
        areasForImprovement: ['Leadership skills', 'Project management'],
        comments: 'Excellent performance this quarter. Sarah has been instrumental in delivering key projects.',
    },
    {
        id: 'perf-0002',
        employeeId: 'emp-0002',
        reviewPeriod: '2025-Q4',
        reviewDate: '2026-01-20',
        reviewer: 'emp-0009',
        overallRating: 4.7,
        technicalSkills: 4.5,
        communication: 4.8,
        teamwork: 4.6,
        leadership: 4.9,
        productivity: 4.5,
        goals: [
            { goal: 'Improve team productivity by 15%', status: 'completed', weight: 0.4 },
            { goal: 'Implement agile methodologies', status: 'completed', weight: 0.3 },
            { goal: 'Reduce technical debt', status: 'in_progress', weight: 0.3 },
        ],
        strengths: ['Excellent leadership', 'Strategic thinking', 'Team development'],
        areasForImprovement: ['Work-life balance', 'Delegation'],
        comments: 'Outstanding leadership. Michael has successfully guided the engineering team through complex projects.',
    },
];

// Training Data
export const trainingData = [
    {
        id: 'train-0001',
        title: 'Leadership Excellence Program',
        type: 'leadership',
        description: 'Comprehensive leadership development program for managers',
        startDate: '2026-03-01',
        endDate: '2026-03-31',
        duration: 40,
        instructor: 'External Consultant',
        maxParticipants: 20,
        currentParticipants: 15,
        status: 'upcoming',
        cost: 2500,
        location: 'Conference Room A',
        participants: ['emp-0002', 'emp-0003', 'emp-0005', 'emp-0007', 'emp-0009'],
    },
    {
        id: 'train-0002',
        title: 'Advanced React Development',
        type: 'technical',
        description: 'Deep dive into advanced React concepts and best practices',
        startDate: '2026-02-15',
        endDate: '2026-02-19',
        duration: 20,
        instructor: 'Sarah Johnson',
        maxParticipants: 15,
        currentParticipants: 12,
        status: 'active',
        cost: 1200,
        location: 'Training Room B',
        participants: ['emp-0001', 'emp-0006', 'emp-0008'],
    },
    {
        id: 'train-0003',
        title: 'Communication Skills Workshop',
        type: 'soft_skills',
        description: 'Improve interpersonal communication and presentation skills',
        startDate: '2026-01-10',
        endDate: '2026-01-12',
        duration: 16,
        instructor: 'HR Department',
        maxParticipants: 25,
        currentParticipants: 22,
        status: 'completed',
        cost: 800,
        location: 'Main Conference Room',
        participants: ['emp-0001', 'emp-0003', 'emp-0004', 'emp-0005', 'emp-0006'],
    },
];

// Benefits Data
export const benefitsData = [
    {
        id: 'ben-0001',
        name: 'Health Insurance',
        type: 'health',
        description: 'Comprehensive medical, dental, and vision coverage',
        eligibility: 'full-time',
        employerContribution: 80,
        employeeContribution: 20,
        enrollmentDeadline: '2026-02-28',
        status: 'active',
        providers: ['Blue Cross Blue Shield', 'Aetna', 'Cigna'],
        plans: [
            { name: 'Basic', monthlyCost: 200, deductible: 5000 },
            { name: 'Standard', monthlyCost: 350, deductible: 2500 },
            { name: 'Premium', monthlyCost: 500, deductible: 1000 },
        ],
    },
    {
        id: 'ben-0002',
        name: '401(k) Retirement Plan',
        type: 'retirement',
        description: 'Company-sponsored 401(k) with employer matching',
        eligibility: 'all_employees',
        employerMatch: 50,
        matchLimit: 6,
        enrollmentDeadline: '2026-03-31',
        status: 'active',
        providers: ['Fidelity', 'Vanguard'],
        vestingSchedule: '3_years',
    },
    {
        id: 'ben-0003',
        name: 'Paid Time Off',
        type: 'time_off',
        description: 'Vacation, sick leave, and personal days',
        eligibility: 'all_employees',
        vacationDays: 20,
        sickDays: 10,
        personalDays: 5,
        enrollmentDeadline: null,
        status: 'active',
        accrualMethod: 'monthly',
    },
];

// Documents Data
export const documentsData = [
    {
        id: 'doc-0001',
        employeeId: 'emp-0001',
        type: 'contract',
        name: 'Employment Agreement',
        description: 'Standard employment contract',
        uploadDate: '2022-03-15',
        expiryDate: '2025-03-15',
        status: 'active',
        fileUrl: '/documents/contracts/emp-0001_contract.pdf',
        size: 245678,
        format: 'PDF',
        required: true,
    },
    {
        id: 'doc-0002',
        employeeId: 'emp-0001',
        type: 'certification',
        name: 'React Developer Certification',
        description: 'Professional React development certification',
        uploadDate: '2023-06-20',
        expiryDate: '2025-06-20',
        status: 'active',
        fileUrl: '/documents/certifications/emp-0001_react.pdf',
        size: 156789,
        format: 'PDF',
        required: false,
    },
    {
        id: 'doc-0003',
        employeeId: 'emp-0002',
        type: 'nda',
        name: 'Non-Disclosure Agreement',
        description: 'Company NDA for management level',
        uploadDate: '2021-01-10',
        expiryDate: null,
        status: 'active',
        fileUrl: '/documents/nda/emp-0002_nda.pdf',
        size: 123456,
        format: 'PDF',
        required: true,
    },
    {
        id: 'doc-0004',
        employeeId: 'emp-0003',
        type: 'performance',
        name: '2025 Performance Review',
        description: 'Annual performance review document',
        uploadDate: '2026-01-15',
        expiryDate: null,
        status: 'active',
        fileUrl: '/documents/performance/emp-0003_review_2025.pdf',
        size: 234567,
        format: 'PDF',
        required: true,
    },
];